# Austin's bash aliases

# Defaults

if ! [ -z "$(command -v z)" ]; then
    alias cd='z'
fi

if ! [ -z "$(command -v lsd)" ]; then
    alias ls='lsd --group-directories-first'
    alias tree='lsd --tree --group-directories-first'
else
    alias ls='ls -F'
fi
alias la='ls -AF'
alias ll='ls -AFl'

alias grep='grep --color=auto'

# Git
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gd="git diff"
alias gf="git fetch"
alias gco="git checkout"
alias gs="git status"
alias gl="git log"
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"

alias cdr='cd "$(git rev-parse --show-toplevel)"'

# Misc

alias config='[ -d ~/dotfiles ] && cd ~/dotfiles || echo "~/dotfiles does not exist"'

alias :q='exit'

# alias oops='sudo $(fc -nl -1)'
function oops() {
    sudo $(fc -nl -1)
}

# vim:ft=bash
