#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom -b --experimental-backends &
nitrogen --restore &
~/.config/polybar/polybar.sh &
xsetroot -cursor_name left_ptr &

# Workspaces
bspc monitor -d 1 2 3 4 5

# Border and gaps
bspc config border_width           4
bspc config window_gap            10

# Border colors
bspc config normal_border_color   "#7F877E"
bspc config active_border_color   "#5D6D7E"
bspc config focused_border_color  "#B73B3B"
# bspc config presel_feedback_color "#92AF8E"

# Cursor
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_modifier      super
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action2       resize_corner

# Misc
bspc config automatic_scheme      alternate
bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       false
