#! /bin/sh

# AUTOSTART
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &
# picom &
nitrogen --restore &
~/.config/bspwm/polybar.sh &

bspc monitor -d I II III IV V

# Border and gaps
bspc config border_width           3
bspc config window_gap            10

# Border colors
bspc config normal_border_color   "#7F877E"
bspc config active_border_color   "#AA7DB1"
bspc config focused_border_color  "#FF2222"
# bspc config presel_feedback_color "#92AF8E"

# Cursor
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_modifier      control

# Misc
bspc config automatic_scheme      longest_side
bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       false
